// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function print(v) {
  var str;
  switch (v.tag | 0) {
    case 0 : 
        str = String(v[0]);
        break;
    case 1 : 
        str = Pervasives.string_of_float(v[0]);
        break;
    case 2 : 
        str = "\"" + (v[0] + "\"");
        break;
    
  }
  console.log(str);
  return /* () */0;
}

function partial_map(values, func) {
  return List.map((function (v) {
                var match = Curry._1(func, v);
                if (match !== undefined) {
                  return match;
                } else {
                  return v;
                }
              }), values);
}

function test(param) {
  var ls$prime = partial_map(/* :: */[
        /* Int */Block.__(0, [5]),
        /* :: */[
          /* String */Block.__(2, ["hello"]),
          /* :: */[
            /* Int */Block.__(0, [2]),
            /* :: */[
              /* Float */Block.__(1, [3.5]),
              /* :: */[
                /* Int */Block.__(0, [16]),
                /* [] */0
              ]
            ]
          ]
        ]
      ], (function (value) {
          switch (value.tag | 0) {
            case 0 : 
                return /* Int */Block.__(0, [(value[0] << 1)]);
            case 1 : 
            case 2 : 
                return undefined;
            
          }
        }));
  return List.iter(print, ls$prime);
}

test(/* () */0);

exports.print = print;
exports.partial_map = partial_map;
exports.test = test;
/*  Not a pure module */
